In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeRegressor

In [2]:
merged = pd.read_csv('merged.csv')
merged.head()

,State,industry,population2020,total unemp,unemp rate,population2019,Density,Total Cases,Total Deaths,Q1 2019,Q2 2019,Q3 2019,Q4 2019,Q1 2020,Q2 2020
0,Alabama,0.5860,3876806.0,166668.0,7.6,3860481.0,96.9221,189149,2914,0.8,0.4,2.8,1.3,-3.2,-29.6
1,Alaska,0.5197,543519.0,42709.0,12.4,544756.0,1.2863,14456,77,0.0,-0.1,3.6,-0.5,-6.0,-33.8
2,Arizona,0.5182,5825181.0,351156.0,10.0,5706551.0,64.9549,242480,5918,2.8,3.0,4.7,4.9,-3.2,-25.3
3,Arkansas,0.5718,2352621.0,106405.0,8.1,2342230.0,58.4030,109712,1894,-1.7,1.5,1.8,1.9,-4.0,-27.9
4,California,0.4155,31219170.0,2830936.0,14.9,31095447.0,256.3728,912904,17541,3.6,4.9,1.6,6.6,-4.3,-31.5

In [3]:
pca = PCA()
X = pca.fit_transform(merged[['unemp rate', 'Q2 2020']])
merged['PCA'] = X[:,0]

In [4]:
pca.explained_variance_ratio_

array([0.88742631, 0.11257369])

In [5]:
cities = merged.sort_values('PCA')[:5]
cities

,State,industry,population2020,total unemp,unemp rate,population2019,Density,Total Cases,Total Deaths,Q1 2019,Q2 2019,Q3 2019,Q4 2019,Q1 2020,Q2 2020,PCA
27,Nevada,0.5997,2471346.0,227426.0,15.2,2421890.0,28.5993,98554,1769,0.5,1.8,4.7,2.7,-4.9,-42.2,-13.990139
10,Hawaii,0.5884,1089320.0,84481.0,13.4,1091223.0,219.9424,14841,214,0.1,-1.0,1.5,2.7,-8.9,-42.2,-13.573755
41,Tennessee,0.5499,5433837.0,305373.0,9.6,5375873.0,167.2749,256880,3263,1.1,1.8,2.5,-0.1,-3.9,-40.4,-10.943545
21,Michigan,0.5442,8008545.0,738476.0,14.9,7990795.0,177.6650,190043,7653,0.9,0.3,3.4,0.9,-7.9,-37.6,-9.445509
44,Vermont,0.6109,518890.0,32452.0,9.5,518151.0,68.1416,2155,58,3.8,-2.8,1.5,0.9,-5.8,-38.2,-8.780084

In [6]:
merged.sort_values('PCA', ascending = False)[:5]

,State,industry,population2020,total unemp,unemp rate,population2019,Density,Total Cases,Total Deaths,Q1 2019,Q2 2019,Q3 2019,Q4 2019,Q1 2020,Q2 2020,PCA
56,China,0.6114,NaN,NaN,3.84,NaN,142.0,91366,4739,NaN,NaN,NaN,NaN,NaN,3.159865,32.767261
54,Japan,0.5758,NaN,NaN,2.80,NaN,339.0,101353,1771,NaN,NaN,NaN,NaN,NaN,-10.100453,20.107184
52,Germany,0.5814,NaN,NaN,4.30,NaN,235.0,517736,10391,NaN,NaN,NaN,NaN,NaN,-11.240518,18.651055
50,Canada,0.5628,NaN,NaN,12.30,NaN,3.0,237313,10187,NaN,NaN,NaN,NaN,NaN,-13.011674,15.077344
53,Italy,0.5346,NaN,NaN,9.40,NaN,197.0,647674,38321,NaN,NaN,NaN,NaN,NaN,-17.949430,10.944357

In [7]:
clf = DecisionTreeRegressor()
features = ['industry', 'Density', 'Total Cases', 'Total Deaths']
clf.fit(merged[features], merged['PCA'])
for i in range(len(features)):
    print(f'Feature Importance of {features[i]}', round(clf.feature_importances_[i], 4))

Feature Importance of industry 0.2005
Feature Importance of Density 0.127
Feature Importance of Total Cases 0.2641
Feature Importance of Total Deaths 0.4083